In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_results_public.csv')

In [5]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [7]:
df.columns = [ x.upper() for x in df.columns]

In [8]:
df

,RESPONDENT,MAINBRANCH,HOBBYIST,OPENSOURCER,OPENSOURCE,EMPLOYMENT,COUNTRY,STUDENT,EDLEVEL,UNDERGRADMAJOR,...,WELCOMECHANGE,SONEWCONTENT,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,DEPENDENTS,SURVEYLENGTH,SURVEYEASE
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [9]:
df.columns = df.columns.str.replace(' ', '_') #replace space with underscore

In [10]:
df

,RESPONDENT,MAINBRANCH,HOBBYIST,OPENSOURCER,OPENSOURCE,EMPLOYMENT,COUNTRY,STUDENT,EDLEVEL,UNDERGRADMAJOR,...,WELCOMECHANGE,SONEWCONTENT,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,DEPENDENTS,SURVEYLENGTH,SURVEYEASE
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [12]:
df.rename(columns = {'RESPONDENT':'re'}) #to make it permanent inplace = true

,re,MAINBRANCH,HOBBYIST,OPENSOURCER,OPENSOURCE,EMPLOYMENT,COUNTRY,STUDENT,EDLEVEL,UNDERGRADMAJOR,...,WELCOMECHANGE,SONEWCONTENT,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,DEPENDENTS,SURVEYLENGTH,SURVEYEASE
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [19]:
df.loc[(1),'HOBBYIST']

'No'

In [24]:
df.loc[1,('RESPONDENT','MAINBRANCH')] = [1,'fuck']

In [25]:
df

,RESPONDENT,MAINBRANCH,HOBBYIST,OPENSOURCER,OPENSOURCE,EMPLOYMENT,COUNTRY,STUDENT,EDLEVEL,UNDERGRADMAJOR,...,WELCOMECHANGE,SONEWCONTENT,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,DEPENDENTS,SURVEYLENGTH,SURVEYEASE
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,1,fuck,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [26]:
#second by using at #while setting value just use .loc or .at

In [27]:
df.at[1,('RESPONDENT','MAINBRANCH')] = [1,'fuck']

In [29]:
df['HOBBYIST'].str.upper()

0        YES
1         NO
2        YES
3         NO
4        YES
        ...
88878    YES
88879     NO
88880     NO
88881     NO
88882    YES
Name: HOBBYIST, Length: 88883, dtype: object

In [30]:
df['HOBBYIST'] = df['HOBBYIST'].str.upper()

In [31]:
df

,RESPONDENT,MAINBRANCH,HOBBYIST,OPENSOURCER,OPENSOURCE,EMPLOYMENT,COUNTRY,STUDENT,EDLEVEL,UNDERGRADMAJOR,...,WELCOMECHANGE,SONEWCONTENT,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,DEPENDENTS,SURVEYLENGTH,SURVEYEASE
0,1,I am a student who is learning to code,YES,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,1,fuck,NO,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",YES,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,NO,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,YES,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,YES,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,NO,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,NO,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,NO,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,YES,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [32]:
#apply 
#map
#applymap

In [36]:
df['COUNTRY'].apply(len) #becuase countryh column contaijns missing valueess

TypeError: object of type 'float' has no len()

In [40]:
def update_country(OPENSOURCER):
    return OPENSOURCER.upper()

In [41]:
df['OPENSOURCER'].apply(update_country)  #applying functions

0                                                    NEVER
1                                  LESS THAN ONCE PER YEAR
2                                                    NEVER
3                                                    NEVER
4                               ONCE A MONTH OR MORE OFTEN
                               ...
88878    LESS THAN ONCE A MONTH BUT MORE THAN ONCE PER ...
88879                                                NEVER
88880                                                NEVER
88881                                                NEVER
88882                              LESS THAN ONCE PER YEAR
Name: OPENSOURCER, Length: 88883, dtype: object

In [43]:
df['OPENSOURCER'] = df['OPENSOURCER'].apply(update_country)

In [44]:
df

,RESPONDENT,MAINBRANCH,HOBBYIST,OPENSOURCER,OPENSOURCE,EMPLOYMENT,COUNTRY,STUDENT,EDLEVEL,UNDERGRADMAJOR,...,WELCOMECHANGE,SONEWCONTENT,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,DEPENDENTS,SURVEYLENGTH,SURVEYEASE
0,1,I am a student who is learning to code,YES,NEVER,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,1,fuck,NO,LESS THAN ONCE PER YEAR,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",YES,NEVER,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,NO,NEVER,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,YES,ONCE A MONTH OR MORE OFTEN,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,YES,LESS THAN ONCE A MONTH BUT MORE THAN ONCE PER ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,NO,NEVER,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,NO,NEVER,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,NO,NEVER,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,YES,LESS THAN ONCE PER YEAR,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [45]:
df['OPENSOURCER'] = df['OPENSOURCER'].apply(lambda x: x.lower()) #lambda functions

,RESPONDENT,MAINBRANCH,HOBBYIST,OPENSOURCER,OPENSOURCE,EMPLOYMENT,COUNTRY,STUDENT,EDLEVEL,UNDERGRADMAJOR,...,WELCOMECHANGE,SONEWCONTENT,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,DEPENDENTS,SURVEYLENGTH,SURVEYEASE
0,1,I am a student who is learning to code,YES,never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,1,fuck,NO,less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",YES,never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,NO,never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,YES,once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,YES,less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,NO,never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,NO,never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,NO,never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,YES,less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [47]:
df.apply(len)

RESPONDENT      88883
MAINBRANCH      88883
HOBBYIST        88883
OPENSOURCER     88883
OPENSOURCE      88883
                ...
SEXUALITY       88883
ETHNICITY       88883
DEPENDENTS      88883
SURVEYLENGTH    88883
SURVEYEASE      88883
Length: 85, dtype: int64

In [49]:
df.apply(len, axis = 'columns')

0        85
1        85
2        85
3        85
4        85
         ..
88878    85
88879    85
88880    85
88881    85
88882    85
Length: 88883, dtype: int64

In [53]:
df.apply(pd.Series.min)  ## not running because float value bhi hai

TypeError: '<=' not supported between instances of 'str' and 'float'

In [55]:
for col in df.columns:
    try:
        df[col].min()
    except TypeError as e:
        print(col, "->", e)
        print(df[col].map(type).value_counts())
        print()

MAINBRANCH -> '<=' not supported between instances of 'str' and 'float'
MAINBRANCH
<class 'str'>      88331
<class 'float'>      552
Name: count, dtype: int64

OPENSOURCE -> '<=' not supported between instances of 'str' and 'float'
OPENSOURCE
<class 'str'>      86842
<class 'float'>     2041
Name: count, dtype: int64

EMPLOYMENT -> '<=' not supported between instances of 'str' and 'float'
EMPLOYMENT
<class 'str'>      87181
<class 'float'>     1702
Name: count, dtype: int64

COUNTRY -> '<=' not supported between instances of 'str' and 'float'
COUNTRY
<class 'str'>      88751
<class 'float'>      132
Name: count, dtype: int64

STUDENT -> '<=' not supported between instances of 'str' and 'float'
STUDENT
<class 'str'>      87014
<class 'float'>     1869
Name: count, dtype: int64

EDLEVEL -> '<=' not supported between instances of 'str' and 'float'
EDLEVEL
<class 'str'>      86390
<class 'float'>     2493
Name: count, dtype: int64

UNDERGRADMAJOR -> '<=' not supported between instances of 'float' and 'str'
UNDERGRADMAJOR
<class 'str'>      75614
<class 'float'>    13269
Name: count, dtype: int64

EDUOTHER -> '<=' not supported between instances of 'str' and 'float'
EDUOTHER
<class 'str'>      84260
<class 'float'>     4623
Name: count, dtype: int64

ORGSIZE -> '<=' not supported between instances of 'float' and 'str'
ORGSIZE
<class 'str'>      71791
<class 'float'>    17092
Name: count, dtype: int64

DEVTYPE -> '<=' not supported between instances of 'float' and 'str'
DEVTYPE
<class 'str'>      81335
<class 'float'>     7548
Name: count, dtype: int64

YEARSCODE -> '<=' not supported between instances of 'str' and 'float'
YEARSCODE
<class 'str'>      87938
<class 'float'>      945
Name: count, dtype: int64

AGE1STCODE -> '<=' not supported between instances of 'str' and 'float'
AGE1STCODE
<class 'str'>      87634
<class 'float'>     1249
Name: count, dtype: int64

YEARSCODEPRO -> '<=' not supported between instances of 'float' and 'str'
YEARSCODEPRO
<class 'str'>      74331
<class 'float'>    14552
Name: count, dtype: int64

CAREERSAT -> '<=' not supported between instances of 'float' and 'str'
CAREERSAT
<class 'str'>      72847
<class 'float'>    16036
Name: count, dtype: int64

JOBSAT -> '<=' not supported between instances of 'float' and 'str'
JOBSAT
<class 'str'>      70988
<class 'float'>    17895
Name: count, dtype: int64

MGRIDIOT -> '<=' not supported between instances of 'float' and 'str'
MGRIDIOT
<class 'str'>      61159
<class 'float'>    27724
Name: count, dtype: int64

MGRMONEY -> '<=' not supported between instances of 'float' and 'str'
MGRMONEY
<class 'str'>      61157
<class 'float'>    27726
Name: count, dtype: int64

MGRWANT -> '<=' not supported between instances of 'float' and 'str'
MGRWANT
<class 'str'>      61232
<class 'float'>    27651
Name: count, dtype: int64

JOBSEEK -> '<=' not supported between instances of 'float' and 'str'
JOBSEEK
<class 'str'>      80555
<class 'float'>     8328
Name: count, dtype: int64

LASTHIREDATE -> '<=' not supported between instances of 'float' and 'str'
LASTHIREDATE
<class 'str'>      79854
<class 'float'>     9029
Name: count, dtype: int64

LASTINT -> '<=' not supported between instances of 'float' and 'str'
LASTINT
<class 'str'>      67155
<class 'float'>    21728
Name: count, dtype: int64

FIZZBUZZ -> '<=' not supported between instances of 'float' and 'str'
FIZZBUZZ
<class 'str'>      71344
<class 'float'>    17539
Name: count, dtype: int64

JOBFACTORS -> '<=' not supported between instances of 'float' and 'str'
JOBFACTORS
<class 'str'>      79371
<class 'float'>     9512
Name: count, dtype: int64

RESUMEUPDATE -> '<=' not supported between instances of 'float' and 'str'
RESUMEUPDATE
<class 'str'>      77877
<class 'float'>    11006
Name: count, dtype: int64

CURRENCYSYMBOL -> '<=' not supported between instances of 'float' and 'str'
CURRENCYSYMBOL
<class 'str'>      71392
<class 'float'>    17491
Name: count, dtype: int64

CURRENCYDESC -> '<=' not supported between instances of 'float' and 'str'
CURRENCYDESC
<class 'str'>      71392
<class 'float'>    17491
Name: count, dtype: int64

COMPFREQ -> '<=' not supported between instances of 'float' and 'str'
COMPFREQ
<class 'str'>      63268
<class 'float'>    25615
Name: count, dtype: int64

WORKPLAN -> '<=' not supported between instances of 'float' and 'str'
WORKPLAN
<class 'str'>      68914
<class 'float'>    19969
Name: count, dtype: int64

WORKCHALLENGE -> '<=' not supported between instances of 'float' and 'str'
WORKCHALLENGE
<class 'str'>      68141
<class 'float'>    20742
Name: count, dtype: int64

WORKREMOTE -> '<=' not supported between instances of 'float' and 'str'
WORKREMOTE
<class 'str'>      70284
<class 'float'>    18599
Name: count, dtype: int64

WORKLOC -> '<=' not supported between instances of 'float' and 'str'
WORKLOC
<class 'str'>      70055
<class 'float'>    18828
Name: count, dtype: int64

IMPSYN -> '<=' not supported between instances of 'float' and 'str'
IMPSYN
<class 'str'>      71779
<class 'float'>    17104
Name: count, dtype: int64

CODEREV -> '<=' not supported between instances of 'float' and 'str'
CODEREV
<class 'str'>      70390
<class 'float'>    18493
Name: count, dtype: int64

UNITTESTS -> '<=' not supported between instances of 'float' and 'str'
UNITTESTS
<class 'str'>      62668
<class 'float'>    26215
Name: count, dtype: int64

PURCHASEHOW -> '<=' not supported between instances of 'float' and 'str'
PURCHASEHOW
<class 'str'>      61108
<class 'float'>    27775
Name: count, dtype: int64

PURCHASEWHAT -> '<=' not supported between instances of 'float' and 'str'
PURCHASEWHAT
<class 'str'>      62029
<class 'float'>    26854
Name: count, dtype: int64

LANGUAGEWORKEDWITH -> '<=' not supported between instances of 'str' and 'float'
LANGUAGEWORKEDWITH
<class 'str'>      87569
<class 'float'>     1314
Name: count, dtype: int64

LANGUAGEDESIRENEXTYEAR -> '<=' not supported between instances of 'str' and 'float'
LANGUAGEDESIRENEXTYEAR
<class 'str'>      84088
<class 'float'>     4795
Name: count, dtype: int64

DATABASEWORKEDWITH -> '<=' not supported between instances of 'str' and 'float'
DATABASEWORKEDWITH
<class 'str'>      76026
<class 'float'>    12857
Name: count, dtype: int64

DATABASEDESIRENEXTYEAR -> '<=' not supported between instances of 'str' and 'float'
DATABASEDESIRENEXTYEAR
<class 'str'>      69147
<class 'float'>    19736
Name: count, dtype: int64

PLATFORMWORKEDWITH -> '<=' not supported between instances of 'str' and 'float'
PLATFORMWORKEDWITH
<class 'str'>      80714
<class 'float'>     8169
Name: count, dtype: int64

PLATFORMDESIRENEXTYEAR -> '<=' not supported between instances of 'str' and 'float'
PLATFORMDESIRENEXTYEAR
<class 'str'>      77443
<class 'float'>    11440
Name: count, dtype: int64

WEBFRAMEWORKEDWITH -> '<=' not supported between instances of 'str' and 'float'
WEBFRAMEWORKEDWITH
<class 'str'>      65022
<class 'float'>    23861
Name: count, dtype: int64

WEBFRAMEDESIRENEXTYEAR -> '<=' not supported between instances of 'str' and 'float'
WEBFRAMEDESIRENEXTYEAR
<class 'str'>      62944
<class 'float'>    25939
Name: count, dtype: int64

MISCTECHWORKEDWITH -> '<=' not supported between instances of 'str' and 'float'
MISCTECHWORKEDWITH
<class 'str'>      59586
<class 'float'>    29297
Name: count, dtype: int64

MISCTECHDESIRENEXTYEAR -> '<=' not supported between instances of 'str' and 'float'
MISCTECHDESIRENEXTYEAR
<class 'str'>      64511
<class 'float'>    24372
Name: count, dtype: int64

DEVENVIRON -> '<=' not supported between instances of 'str' and 'float'
DEVENVIRON
<class 'str'>      87317
<class 'float'>     1566
Name: count, dtype: int64

OPSYS -> '<=' not supported between instances of 'str' and 'float'
OPSYS
<class 'str'>      87851
<class 'float'>     1032
Name: count, dtype: int64

CONTAINERS -> '<=' not supported between instances of 'str' and 'float'
CONTAINERS
<class 'str'>      85366
<class 'float'>     3517
Name: count, dtype: int64

BLOCKCHAINORG -> '<=' not supported between instances of 'float' and 'str'
BLOCKCHAINORG
<class 'str'>      48175
<class 'float'>    40708
Name: count, dtype: int64

BLOCKCHAINIS -> '<=' not supported between instances of 'float' and 'str'
BLOCKCHAINIS
<class 'str'>      60165
<class 'float'>    28718
Name: count, dtype: int64

BETTERLIFE -> '<=' not supported between instances of 'str' and 'float'
BETTERLIFE
<class 'str'>      86269
<class 'float'>     2614
Name: count, dtype: int64

ITPERSON -> '<=' not supported between instances of 'str' and 'float'
ITPERSON
<class 'str'>      87141
<class 'float'>     1742
Name: count, dtype: int64

OFFON -> '<=' not supported between instances of 'str' and 'float'
OFFON
<class 'str'>      86663
<class 'float'>     2220
Name: count, dtype: int64

SOCIALMEDIA -> '<=' not supported between instances of 'str' and 'float'
SOCIALMEDIA
<class 'str'>      84437
<class 'float'>     4446
Name: count, dtype: int64

EXTRAVERSION -> '<=' not supported between instances of 'str' and 'float'
EXTRAVERSION
<class 'str'>      87305
<class 'float'>     1578
Name: count, dtype: int64

SCREENNAME -> '<=' not supported between instances of 'str' and 'float'
SCREENNAME
<class 'str'>      80486
<class 'float'>     8397
Name: count, dtype: int64

SOVISIT1ST -> '<=' not supported between instances of 'str' and 'float'
SOVISIT1ST
<class 'str'>      83877
<class 'float'>     5006
Name: count, dtype: int64

SOVISITFREQ -> '<=' not supported between instances of 'str' and 'float'
SOVISITFREQ
<class 'str'>      88263
<class 'float'>      620
Name: count, dtype: int64

SOVISITTO -> '<=' not supported between instances of 'str' and 'float'
SOVISITTO
<class 'str'>      88086
<class 'float'>      797
Name: count, dtype: int64

SOFINDANSWER -> '<=' not supported between instances of 'str' and 'float'
SOFINDANSWER
<class 'str'>      87816
<class 'float'>     1067
Name: count, dtype: int64

SOTIMESAVED -> '<=' not supported between instances of 'str' and 'float'
SOTIMESAVED
<class 'str'>      86344
<class 'float'>     2539
Name: count, dtype: int64

SOHOWMUCHTIME -> '<=' not supported between instances of 'str' and 'float'
SOHOWMUCHTIME
<class 'str'>      68378
<class 'float'>    20505
Name: count, dtype: int64

SOACCOUNT -> '<=' not supported between instances of 'str' and 'float'
SOACCOUNT
<class 'str'>      87828
<class 'float'>     1055
Name: count, dtype: int64

SOPARTFREQ -> '<=' not supported between instances of 'float' and 'str'
SOPARTFREQ
<class 'str'>      74692
<class 'float'>    14191
Name: count, dtype: int64

SOJOBS -> '<=' not supported between instances of 'str' and 'float'
SOJOBS
<class 'str'>      88066
<class 'float'>      817
Name: count, dtype: int64

ENTTEAMS -> '<=' not supported between instances of 'str' and 'float'
ENTTEAMS
<class 'str'>      87841
<class 'float'>     1042
Name: count, dtype: int64

SOCOMM -> '<=' not supported between instances of 'str' and 'float'
SOCOMM
<class 'str'>      88131
<class 'float'>      752
Name: count, dtype: int64

WELCOMECHANGE -> '<=' not supported between instances of 'str' and 'float'
WELCOMECHANGE
<class 'str'>      85855
<class 'float'>     3028
Name: count, dtype: int64

SONEWCONTENT -> '<=' not supported between instances of 'str' and 'float'
SONEWCONTENT
<class 'str'>      69560
<class 'float'>    19323
Name: count, dtype: int64

GENDER -> '<=' not supported between instances of 'str' and 'float'
GENDER
<class 'str'>      85406
<class 'float'>     3477
Name: count, dtype: int64

TRANS -> '<=' not supported between instances of 'str' and 'float'
TRANS
<class 'str'>      83607
<class 'float'>     5276
Name: count, dtype: int64

SEXUALITY -> '<=' not supported between instances of 'str' and 'float'
SEXUALITY
<class 'str'>      76147
<class 'float'>    12736
Name: count, dtype: int64

ETHNICITY -> '<=' not supported between instances of 'float' and 'str'
ETHNICITY
<class 'str'>      76668
<class 'float'>    12215
Name: count, dtype: int64

DEPENDENTS -> '<=' not supported between instances of 'str' and 'float'
DEPENDENTS
<class 'str'>      83059
<class 'float'>     5824
Name: count, dtype: int64

SURVEYLENGTH -> '<=' not supported between instances of 'str' and 'float'
SURVEYLENGTH
<class 'str'>      86984
<class 'float'>     1899
Name: count, dtype: int64

SURVEYEASE -> '<=' not supported between instances of 'str' and 'float'
SURVEYEASE
<class 'str'>      87081
<class 'float'>     1802
Name: count, dtype: int64

In [56]:
df.applymap(len)

C:\Users\garvi\AppData\Local\Temp\ipykernel_17840\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

TypeError: object of type 'int' has no len()